apiVersion: v1
kind: Pod
metadata:
  name: elegant-bell
  namespace: default
  labels: {app: nextflow, runName: elegant-bell}
spec:
  restartPolicy: Never
  containers:
  - name: elegant-bell
    image: nextflow/nextflow:24.08.0-edge
    command: [/bin/bash, -c, source /etc/nextflow/init.sh; nextflow run nf-core/rnaseq
        -name elegant-bell -r 4053b2ec173fc0cfdd13ff2b51cfaceb59f783cb]
    env:
    - {name: NXF_WORK, value: /mnt/data/cao-thanj/work}
    - {name: NXF_ASSETS, value: /mnt/data/projects}
    - {name: NXF_EXECUTOR, value: k8s}
    - {name: NXF_ANSI_LOG, value: 'false'}
    volumeMounts:
    - {name: vol-1, mountPath: /mnt/data}
    - {name: vol-2, mountPath: /etc/nextflow}
  serviceAccountName: default
  volumes:
  - name: vol-1
    persistentVolumeClaim: {claimName: nextflow-pvc}
  - name: vol-2
    configMap: {name: nf-config-1644ku8w}