apiVersion: v1
kind: Pod
metadata:
  name: stoic-hertz
  namespace: default
  labels: {app: nextflow, runName: stoic-hertz}
spec:
  restartPolicy: Never
  containers:
  - name: stoic-hertz
    image: nextflow/nextflow:24.08.0-edge
    command: [/bin/bash, -c, source /etc/nextflow/init.sh; nextflow run thanhct/nf-hello4
        -name stoic-hertz -r e970cf7 --debug true]
    env:
    - {name: NXF_WORK, value: /mnt/data/cao-thanj/work}
    - {name: NXF_ASSETS, value: /mnt/data/projects}
    - {name: NXF_EXECUTOR, value: k8s}
    - {name: NXF_ANSI_LOG, value: 'false'}
    volumeMounts:
    - {name: vol-1, mountPath: /mnt/data}
    - {name: vol-2, mountPath: /etc/nextflow}
  serviceAccountName: default
  volumes:
  - name: vol-1
    persistentVolumeClaim: {claimName: nextflow-pvc}
  - name: vol-2
    configMap: {name: nf-config-y6m4515s}