---
kind: ConfigMap
apiVersion: v1
metadata:
  name: nf-config-hcjki3ar
  namespace: default
  uid: 2085f297-d9a4-4e98-a888-0f734257151c
  resourceVersion: '0'
  creationTimestamp: '2024-10-23T10:14:07Z'
  managedFields:
    - manager: Java
      operation: Update
      apiVersion: v1
      time: '2024-10-23T10:14:07Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:init.sh: {}
          f:nextflow.config: {}
data:
  init.sh: >-
    mkdir -p '/mnt/data/cao-thanj'; if [ -d '/mnt/data/cao-thanj' ]; then cd
    '/mnt/data/cao-thanj'; else echo 'Cannot create directory:
    /mnt/data/cao-thanj'; exit 1; fi; [ -f /etc/nextflow/scm ] && ln -s
    /etc/nextflow/scm $NXF_HOME/scm; [ -f /etc/nextflow/nextflow.config ] && cp
    /etc/nextflow/nextflow.config $PWD/nextflow.config; 
  nextflow.config: |
    process {
       executor = 'k8s'
       container = 'nextflow/rnaseq-nf'
    }

    k8s {
       namespace = 'default'
       serviceAccount = 'default'
       storageClaimName = 'nextflow-pvc'
       storageMountPath = '/mnt/data'
    }

    params {
       config_profile_name        = 'Test profile'
      config_profile_description = 'Minimal test dataset to check pipeline function'
      outdir = '/mnt/data/outdir'

      // Limit resources so that this can run on GitHub Actions
      max_cpus   = 2
      max_memory = '6.GB'
      max_time   = '6.h'
      // Input data
      input              = 'https://raw.githubusercontent.com/nf-core/test-datasets/626c8fab639062eade4b10747e919341cbf9b41a/samplesheet/v3.10/samplesheet_test.csv'
      // Genome references
      fasta              = 'https://raw.githubusercontent.com/nf-core/test-datasets/626c8fab639062eade4b10747e919341cbf9b41a/reference/genome.fasta'
      gtf                = 'https://raw.githubusercontent.com/nf-core/test-datasets/626c8fab639062eade4b10747e919341cbf9b41a/reference/genes_with_empty_tid.gtf.gz'
      gff                = 'https://raw.githubusercontent.com/nf-core/test-datasets/626c8fab639062eade4b10747e919341cbf9b41a/reference/genes.gff.gz'
      transcript_fasta   = 'https://raw.githubusercontent.com/nf-core/test-datasets/626c8fab639062eade4b10747e919341cbf9b41a/reference/transcriptome.fasta'
      additional_fasta   = 'https://raw.githubusercontent.com/nf-core/test-datasets/626c8fab639062eade4b10747e919341cbf9b41a/reference/gfp.fa.gz'

      bbsplit_fasta_list = 'https://raw.githubusercontent.com/nf-core/test-datasets/626c8fab639062eade4b10747e919341cbf9b41a/reference/bbsplit_fasta_list.txt'
      hisat2_index       = 'https://raw.githubusercontent.com/nf-core/test-datasets/626c8fab639062eade4b10747e919341cbf9b41a/reference/hisat2.tar.gz'
      salmon_index       = 'https://raw.githubusercontent.com/nf-core/test-datasets/626c8fab639062eade4b10747e919341cbf9b41a/reference/salmon.tar.gz'
      rsem_index         = 'https://raw.githubusercontent.com/nf-core/test-datasets/626c8fab639062eade4b10747e919341cbf9b41a/reference/rsem.tar.gz'

      // Other parameters
      skip_bbsplit        = false
      pseudo_aligner      = 'salmon'
      umitools_bc_pattern = 'NNNN'
    }

    runName = '${NF_RUN_NAME}'